### ISSUE TITLE
Packaging for Foreman-plugins deb and rpm?

### ISSUE THREAD

**Issue by howels** [theforeman/smart_proxy_dhcp_infoblox#13]
Is there an ETA for packaging of this module into the relevant foreman plugins packages? 

Currently we are unable to wipe and redeploy from Gems and the instructions for integrating Gems into a from-package deployment with Ubuntu do not work (using Foreman-proxy 1.12.1).

**Comment by iNecas** [comment]
We are tracking this in http://projects.theforeman.org/issues/15852, aiming for Foreman 1.13, withing the nearest weeks
