### ISSUE TITLE
Supported foreman/foreman-proxy versions ?

### ISSUE THREAD

**Issue by pdd13** [theforeman/smart_proxy_dhcp_infoblox#17]
Installing latest 0.0.5 on a 1.12.3 foreman/proxy version gets me 

Disabling all modules in the group ['dhcp_infoblox', 'dhcp'] due to a failure in one of them: Available version '1.12.3' of 'dhcp' doesn't match version '>= 1.13' required by 'dhcp_infoblox'

Description states support for 1.11+

Rolling back to smart_proxy_dhcp_infoblox version 0.0.4 kinda works with a number of fixes, BUT then the network ranges are not supported, which is a really nice feature (instead of polling all)

Any comment/help on this one ?

**Comment by pdd13** [comment]
Block in question

`  def validate_dependencies!(plugin, dependencies, enabled_providers_and_plugins)
    dependencies.each do |dep|
      found = enabled_providers_and_plugins[dep.name]
      raise ::Proxy::PluginNotFound, "'#{dep.name}' required by '#{plugin.plugin_name}' could not be found." unless found
      unless ::Gem::Dependency.new('', dep.version).match?('', found.cleanup_version(found.version))
        raise ::Proxy::PluginVersionMismatch, "Available version '#{found.version}' of '#{dep.name}' doesn't match version '#{dep.version}' required by '#{plugin.plugin_name}'"
      end
    end
  end`

**Comment by pdd13** [comment]
Commented out the check - not running anything else on this proxy anyway :)
Now test test test

**Comment by witlessbird** [comment]
I'm going to close this issue. Please use https://community.theforeman.org/ for new support questions.
