### ISSUE TITLE
Returning incorrect network's IPs in unused_network_ip

### ISSUE THREAD

**Issue by 01100010011001010110010101110000** [theforeman/smart_proxy_dhcp_infoblox#28]
I believe this is because there is an error in ```find_network```

Using ```'network~'``` as the search parameter has an issue when one has networks of, for example:
* 172.18.2.0/24
* 172.18.200.0/24
* 172.18.210.0/24
* 172.18.220.0/24
* 172.18.230.0/24
* 172.18.240.0/24
* 172.18.250.0/24

On a request to ```GET /network?network~=172.18.2.0/24``` Infoblox will return all of the above subnets, and in no particular order. Because ```find_network``` returns only the first result, it may or may not use the correct network to retrieve a free IP address.

**Comment by witlessbird** [comment]
Fix is available in PR: https://github.com/theforeman/smart_proxy_dhcp_infoblox/pull/31

**Comment by witlessbird** [comment]
Closing the issue, the fix has been merged.
