### ISSUE TITLE
Can't create host object without specifying host.view

### ISSUE THREAD

**Issue by wiad** [theforeman/smart_proxy_dhcp_infoblox#30]
We have several views in InfoBlox and I had to hardcode the correct one to get host object creation to work. 

I added the line
`host.view = 'Internal'`

to the 'build_host' define in lib/smart_proxy_dhcp_infoblox/host_ipv4_address_crud.rb. 

Should this be an configurable option? If so, what is the default? I'll be happy to create a PR if this seems legit to you.

**Comment by wiad** [comment]
Just saw that there is a PR for this same issue on the smart_proxy_dns_infoblox project:

https://github.com/theforeman/smart_proxy_dns_infoblox/pull/16

Should be pretty much the same code implementation

**Comment by witlessbird** [comment]
This PR should fix the issue: https://github.com/theforeman/smart_proxy_dhcp_infoblox/pull/32

**Comment by witlessbird** [comment]
The issue has been fixed in the latest release of smart_proxy_dhcp_infoblox gem.
