### ISSUE TITLE
Unable to retrieve DHCP entry

### ISSUE THREAD

**Issue by wiad** [theforeman/smart_proxy_dhcp_infoblox#33]
I'm getting the following error message when i'm trying to edit a host:
```
ProxyAPI::ProxyException: ERF12-4395 [ProxyAPI::ProxyException]: Unable to retrieve DHCP entry for 172.29.0.187 ([NoMethodError]: undefined method `merge' for nil:NilClass) for proxy ...
/usr/share/foreman/lib/proxy_api/dhcp.rb:76:in `rescue in records_by_ip'
...
```

Upon further inspection I have traced it to the `find_records_by_ip` function in `host_ipv4_address_crud.rb`. If you don't have a dhcp reservation for the server (which I dont since we use static addresses) the `build_reservation` function called from this function will return 'nil', which in conjunction with the 'map' function used here will result in a return value from the  `find_records_by_ip` function looking like `[null]`. This return value is not accepted by the foreman-proxy resulting in the error message. 

If I check the 'dhcp' checkbox in InfoBlox for my server host objects the `find_records_by_ip` returns a more sane result:
`[{"name":"lxserv940.example.com","ip":"172.29.0.187","mac":"00:50:56:be:50:d5","subnet":"172.29.0.0/255.255.252.0","type":"reservation","hostname":"lxserv940.example.com","deleteable":true}]`

Proposed solution by this ruby noob is to check the result from the `build_reservation` call before returning it - only return if it contains any real data (.any?), otherwise return `[]`.

So this code works for me:

```
def find_records_by_ip(subnet_address, ip_address)
  found = find_hosts({'ipv4addr' => ip_address}, 2147483646)
  return [] if found.empty?
  foundmap = found.map {|record| build_reservation(record.name, record.ipv4addrs.find {|ip| ip.ipv4addr == ip_address}, subnet_address)}
  # Return array if it contains any data
  return foundmap if foundmap.any?
  # Otherwise return empty array
  return []
def
```

**Comment by wiad** [comment]
One more thing - when the infoblox provider in Foreman creates host objects in Infoblox it activates dhcp config (i.e. the 'dhcp checkbox') for that object by default. So for all objects created via Foreman the current behaviour will work, but if you have host objects that are not created by Foreman or for some other reason do not have the dhcp config activated Foreman will react with an error rather than just saying that it couldnt find any object, which is wrong in my opinion.

**Comment by wiad** [comment]
I worked around this by enabling dhcp for all my host objects in infoblox. But then I stumbled upon another case - a host that has two host objects in infoblox with the same ip address but different zones. Only one of the objects has dhcp activated (both cant have it since it is the mac is already registered on one of the objects). This returns a result of:
`[{"name":"lxserv1133.example.com","ip":"172.29.32.19","mac":"00:50:56:93:93:e4","subnet":"172.29.32.0/255.255.255.0","type":"reservation","hostname":"lxserv1133.example.com","deleteable":true},null]`

Notice that there are two elements in the array, since there are two objects with this ip address in infoblox, but since one of them does not have dhcp activated the output is again `null`. 

I have worked around this by removing empty array elements:
`foundmap.reject { |c| c.to_s.empty? }`

but maybe this should be managed in `build_reservation` instead?

**Comment by wiad** [comment]
Another situation where this error happens if is you have a wildcard a record on an ip that is also used for a host a record. The host a record, complete with activated dhcp, is found by the infoblox proxy but the wildcard record is returned as 'null'.

**Comment by witlessbird** [comment]
These should be fixed by changes in https://github.com/theforeman/smart_proxy_dhcp_infoblox/commit/9b68b7b98ba77e90cf7b5421fc7feb45280dccd9. Could you give it a try (you'll need to use source-based install, as I have yet to release gem and rpm packages with the changes)?

**Comment by witlessbird** [comment]
Published a new version of the gem containing the fixes.

**Comment by witlessbird** [comment]
I'm going to close the issue, please open a new one if the issue described above persists.
