### ISSUE TITLE
record_type for fixed address allocation is wrong in configuration comments

### ISSUE THREAD

**Issue by cmeissner** [theforeman/smart_proxy_dhcp_infoblox#35]
We switched our dhcp_infoblox provider from record_type "host" to "fixed_address" as shown in example configuration. But after that dhcp_infoblox vanished. 
A grep in source code of the plugin shows that the correct value is "fixedaddress".

**Comment by witlessbird** [comment]
This has been fixed in version 0.0.8: https://github.com/theforeman/smart_proxy_dhcp_infoblox/commit/f87a1a83f2a3e3e8cad2c241b56695bd99c85c1a
