### ISSUE TITLE
Upgrade to 0.12 breaks the unused_ip call

### ISSUE THREAD

**Issue by sbskas** [theforeman/smart_proxy_dhcp_infoblox#37]
After upgrade of the smart_proxy_dhcp_infoblox, the foreman_proxy isn't able to find a new IP address.
It logs an error  like this :
> D, [2018-04-26T11:30:48.484284 118f6fc9] DEBUG -- : verifying remote client 10.24.48.201 against trusted_hosts ["front01-tool.phys.prod", "front02-tool.phys.prod", "vip-http01-tool.phys.prod"]
>E, [2018-04-26T11:30:52.722376 118f6fc9] ERROR -- : undefined method `subnet_range_addresses' for "255.255.252.0":String
>D, [2018-04-26T11:30:52.722487 118f6fc9] DEBUG -- : undefined method `subnet_range_addresses' for "255.255.252.0":String (NoMethodError)

Problem is related to the get_subnet function that doesn't returne the correct value.
I opened pull request [36](https://github.com/theforeman/smart_proxy_dhcp_infoblox/pull/36l) to fix this.

**Comment by witlessbird** [comment]
I created a ticket in redmine (http://projects.theforeman.org/issues/23412) to track this issue. Please use it for further updates

**Comment by witlessbird** [comment]
Fixed in https://github.com/theforeman/smart_proxy_dhcp_infoblox/pull/36.
