### ISSUE TITLE
AdmConDataNotFoundError: View default not found

### ISSUE THREAD

**Issue by cmeissner** [theforeman/smart_proxy_dhcp_infoblox#38]
If we use the lastest gem version (0.0.13) we get the following Stacktrace if we ask for new IP-Address via `/dhcp/AAA.BBB.CCC.DDD/unused_ip`

    E, [2018-04-30T08:54:49.168211 ] ERROR -- : Error: 404 { "Error": "AdmConDataNotFoundError: View default not found", 
      "code": "Client.Ibap.Data.NotFound", 
      "text": "View default not found", 
      "trace": "  File \"ibapapachemod.py\", line 449, in handlerequest\n  File \"/infoblox/common/lib/python/infoblox/one/admin_conn/wapibase.py\", line 1429, in execute\n  File \"/infoblox/common/lib/python/infoblox/one/admin_conn/wapibase.py\", line 1384, in _exec_handler\n  File \"/infoblox/common/lib/python/infoblox/one/admin_conn/wapihandler.py\", line 712, in execute\n  File \"/infoblox/common/lib/python/infoblox/one/wapibaseobj.py\", line 1245, in read\n  File \"/infoblox/common/lib/python/infoblox/one/wapibaseobj.py\", line 316, in make_searchfields_dict\n  File \"/infoblox/common/lib/python/infoblox/one/wapibaseobj.py\", line 297, in add_search_info\n  File \"/infoblox/common/lib/python/infoblox/dns/wapi/dns.py\", line 116, in w2i\n  File \"/infoblox/common/lib/python/infoblox/dns/wapi/dns.py\", line 65, in viewname2view\n"
    }
    D, [2018-04-30T08:54:49.168307 ] DEBUG -- : Error: 404 { "Error": "AdmConDataNotFoundError: View default not found", 
      "code": "Client.Ibap.Data.NotFound", 
      "text": "View default not found", 
      "trace": "  File \"ibapapachemod.py\", line 449, in handlerequest\n  File \"/infoblox/common/lib/python/infoblox/one/admin_conn/wapibase.py\", line 1429, in execute\n  File \"/infoblox/common/lib/python/infoblox/one/admin_conn/wapibase.py\", line 1384, in _exec_handler\n  File \"/infoblox/common/lib/python/infoblox/one/admin_conn/wapihandler.py\", line 712, in execute\n  File \"/infoblox/common/lib/python/infoblox/one/wapibaseobj.py\", line 1245, in read\n  File \"/infoblox/common/lib/python/infoblox/one/wapibaseobj.py\", line 316, in make_searchfields_dict\n  File \"/infoblox/common/lib/python/infoblox/one/wapibaseobj.py\", line 297, in add_search_info\n  File \"/infoblox/common/lib/python/infoblox/dns/wapi/dns.py\", line 116, in w2i\n  File \"/infoblox/common/lib/python/infoblox/dns/wapi/dns.py\", line 65, in viewname2view\n"
    } (Infoblox::Error)
    /var/lib/gems/2.3.0/gems/infoblox-2.0.5/lib/infoblox/connection.rb:89:in `block in wrap'
    /var/lib/gems/2.3.0/gems/infoblox-2.0.5/lib/infoblox/connection.rb:87:in `tap'
    /var/lib/gems/2.3.0/gems/infoblox-2.0.5/lib/infoblox/connection.rb:87:in `wrap'
    /var/lib/gems/2.3.0/gems/infoblox-2.0.5/lib/infoblox/connection.rb:16:in `get'
    /var/lib/gems/2.3.0/gems/infoblox-2.0.5/lib/infoblox/resource.rb:110:in `find'
    /var/lib/gems/2.3.0/gems/smart_proxy_dhcp_infoblox-0.0.13/lib/smart_proxy_dhcp_infoblox/host_ipv4_address_crud.rb:18:in `all_hosts'
    /var/lib/gems/2.3.0/gems/smart_proxy_dhcp_infoblox-0.0.13/lib/smart_proxy_dhcp_infoblox/dhcp_infoblox_main.rb:31:in `all_hosts'
    /usr/share/foreman-proxy/modules/dhcp_common/server.rb:101:in `unused_ip'
    /usr/share/foreman-proxy/modules/dhcp/dhcp_api.rb:34:in `block in <class:DhcpApi>'
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1611:in `call'
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1611:in `block in compile!'
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb:975:in `block (3 levels) in route!'
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb:994:in `route_eval'
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb:975:in `block (2 levels) in route!'
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1015:in `block in process_route'
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1013:in `catch'
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1013:in `process_route'
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb:973:in `block in route!'
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb:972:in `each'
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb:972:in `route!'
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1085:in `block in dispatch!'
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1067:in `block in invoke'
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1067:in `catch'
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1067:in `invoke'
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1082:in `dispatch!'
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb:907:in `block in call!'
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1067:in `block in invoke'
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1067:in `catch'
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1067:in `invoke'
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb:907:in `call!'
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb:895:in `call'
    /usr/lib/ruby/vendor_ruby/rack/methodoverride.rb:22:in `call'
    /usr/lib/ruby/vendor_ruby/rack/commonlogger.rb:33:in `call'
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb:219:in `call'
    /usr/share/foreman-proxy/lib/proxy/log.rb:109:in `call'
    /usr/share/foreman-proxy/lib/proxy/request_id_middleware.rb:9:in `call'
    /usr/lib/ruby/vendor_ruby/rack/protection/xss_header.rb:18:in `call'
    /usr/lib/ruby/vendor_ruby/rack/protection/path_traversal.rb:16:in `call'
    /usr/lib/ruby/vendor_ruby/rack/protection/json_csrf.rb:18:in `call'
    /usr/lib/ruby/vendor_ruby/rack/protection/base.rb:49:in `call'
    /usr/lib/ruby/vendor_ruby/rack/protection/base.rb:49:in `call'
    /usr/lib/ruby/vendor_ruby/rack/protection/frame_options.rb:31:in `call'
    /usr/lib/ruby/vendor_ruby/rack/nulllogger.rb:9:in `call'
    /usr/lib/ruby/vendor_ruby/rack/head.rb:13:in `call'
    /usr/lib/ruby/vendor_ruby/sinatra/show_exceptions.rb:25:in `call'
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb:182:in `call'
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb:2013:in `call'
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1487:in `block in call'
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1787:in `synchronize'
    /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1487:in `call'
    /usr/lib/ruby/vendor_ruby/rack/urlmap.rb:66:in `block in call'
    /usr/lib/ruby/vendor_ruby/rack/urlmap.rb:50:in `each'
    /usr/lib/ruby/vendor_ruby/rack/urlmap.rb:50:in `call'
    /usr/lib/ruby/vendor_ruby/rack/builder.rb:153:in `call'
    /usr/lib/ruby/vendor_ruby/rack/handler/webrick.rb:88:in `service'
    /usr/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
    /usr/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
    /usr/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
    I, [2018-04-30T08:54:49.169272 ]  INFO -- : 127.0.0.1 - - [30/Apr/2018:08:54:49 +0200] "GET /dhcp/AAA.BBB.CCC.DDD/unused_ip HTTP/1.1" 400 994 0.2601

Our Infoblox has no extra network view configured. All objects are accessible under the default network view.

**Comment by witlessbird** [comment]
I don't have documentation for infoblox errors, and as a rule would like to avoid re-writing errors generated by third-party systems.

FWIW, 

```
E, [2018-04-30T08:54:49.168211 ] ERROR -- : Error: 404 { "Error": "AdmConDataNotFoundError: View default not found", 
  "code": "Client.Ibap.Data.NotFound", 
  "text": "View default not found", 
 ... }
```

Contains a decent explanation of what went wrong.
