### ISSUE TITLE
Foreman can't get a free ip in networks greater then /24

### ISSUE THREAD

**Issue by cmeissner** [theforeman/smart_proxy_dhcp_infoblox#39]
We have a /23 network and here foreman does not be able to get a free ip address. 

    # curl 'http://localhost:8000/dhcp/10.176.228.0/unused_ip?from=10.176.228.4&to=10.176.228.254'
    {"ip":null}

With or without a range we get the same result. We also create a new /22 network to verify the behavior and it's the same.

![screenshot_2018-04-30_10-07-56](https://user-images.githubusercontent.com/14936920/39419110-8532f1c6-4c5e-11e8-8db7-aa1e3753b1bc.png)

Here the way we configured the network in foreman.

**Comment by grimmsen** [comment]
As a reissurance foreman-proxy probes the host with icmp and tcp-echo-requests. If this check does not result in a timeout, reservation fails, even if the IP is marked as unused in the IPAM.
In this particular case, the TCP-echo-request resulted in "Connection refused" regardless if the host is up or not. 
We have to fix this on network level. 
Just in case, somebody else has that problem, check the IP with a telnet on port 7. A timeout is good, a "connection refused" is bad, when you definitly know the host is down.

**Comment by witlessbird** [comment]
Please use http://projects.theforeman.org/projects/infoblox for reporting new issues. Please use https://community.theforeman.org/ and/or #theforeman irc channel for support questions.

I assume you are seeing this issue with version 0.0.13 of the gem? If so, @grimmsen's explanation is most likely correct. Smart-proxy's log might provide additional insight.

**Comment by grimmsen** [comment]
@witlessbird I may have to object here. Despite the good intention, this behaviour is less than ideal and should have an off switch. In situations where the probe leaves its own network (i.e. another vlan) a firewall might block the echo request to a host that is up, but is not managed by the ipam and will result a timeout, respectively in a false positive. I that case it was the other way arround, but it revealed this odd decision making process by foreman-proxy.
Maybe a switch like "no_ping_probe" will make this behaviour more obvious to the user. 
Just my two cents.

**Comment by lzap** [comment]
Hello, PINGing was made optional in the latest versions of project and products. Setting name is `ping_free_ip`. About the "network graeter then" - file an issue on our tracker.
